config/routes.rb
Osb::Application.routes.draw do

  resources :sub_users

  resources :payment_terms

  resources :companies

  match "help" => "help#index"
  match "reports/:report_name" => "reports#reports"
  match "reports/data/:report_name" => "reports#reports_data"
  match "reports" => "reports#index"

  match "dashboard" => "dashboard#index"
  resources :payments do
    collection do
      get 'enter_payment'
      put 'update_individual_payment'
      get 'filter_payments'
      get 'bulk_actions'
      get 'undo_actions'
      get 'payments_history'
      get 'invoice_payments_history'
    end
  end
  resources :taxes do
    collection do
      get 'filter_taxes'
      get 'bulk_actions'
      get 'undo_actions'
    end
  end

  match "invoices/unpaid_invoices" => "invoices#unpaid_invoices"

  resources :clients do
    collection do
      get 'filter_clients'
      get 'bulk_actions'
      post 'get_last_invoice'
      get 'undo_actions'
    end
  end

  resources :client_contacts

  devise_for :users, :path_names => {:sign_out => 'logout'}

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

  resources :items do
    collection do
      get 'filter_items'
      get 'bulk_actions'
      post 'load_item_data'
      get 'duplicate_item'
      get 'undo_actions'
    end
  end

  resources :invoice_line_items

  resources :invoices do
    resources :invoice_line_items
    collection do
      get 'filter_invoices'
      get 'bulk_actions'
      get 'undo_actions'
      post 'duplicate_invoice'
      get 'enter_single_payment'
      get 'send_invoice'
      post 'paypal_payments'
      get 'preview'
      get 'credit_card_info'
    end
  end

  resources :company_profiles

  resources :client_additional_contacts

  resources :clients

  resources :sent_emails

  root :to => redirect("/dashboard")

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/dashboard_controller.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
class DashboardController < ApplicationController
  def index
    @recent_activity = Reporting::Dashboard.get_recent_activity
    gon.chart_data = Reporting::Dashboard.get_chart_data
    @aged_invoices = Reporting::Dashboard.get_aging_data
    @outstanding_invoices = (@aged_invoices.attributes["zero_to_thirty"] || 0) +
        (@aged_invoices.attributes["thirty_one_to_sixty"] || 0) +
        (@aged_invoices.attributes["sixty_one_to_ninety"] || 0) +
        (@aged_invoices.attributes["ninety_one_and_above"] || 0)
    @current_invoices = Invoice.current_invoices
    @past_invoices = Invoice.past_invoices
    @amount_billed = Invoice.total_invoices_amount
    @outstanding_invoices = Reporting::Dashboard.get_outstanding_invoices
    @ytd_income = Reporting::Dashboard.get_ytd_income
  end
end

app/helpers/dashboard_helper.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
module DashboardHelper
  def invoices_by_period period
    Reporting::Dashboard.get_invoices_by_period period
  end
end

app/views/dashboard/_chart_container.html.erb
<div class="graph_wrapper">
  <div class="dashboard_box">
    <div class="heading">
      <h1>Invoices <span>(USD)</span></h1>
    </div>
    <div class="graph_content">
      <div id="dashboard-chart" style="height: 191px; width: 100%;"></div>
      <%#= image_tag "graph.png", :size => "447x191", :alt => "" %>
    </div>
  </div>
</div>

app/views/dashboard/_getting_started.html.erb
<div class="overview_box">

  <div class="overview_box_heading">
    <h1 class="small">Getting Started</h1>
  </div>
  <div class="getting_start">
    <ul>
      <li><%= link_to "Create new invoice", new_invoice_path %></li>
      <li><%= link_to "Create new item", new_item_path %></li>
      <li><%= link_to "Create new client", new_client_path %></li>
      <li><%= link_to "Enter payment", '/invoices/unpaid_invoices', "data-toggle" => "modal", "data-target" => "#myModal", :remote => true %></li>
    </ul>
  </div>
</div><!--overview_box-->

app/views/dashboard/_osb_reports.html.erb
<div class="overview_box">
  <div class="overview_box_heading">
    <h1 class="small">OSB Reports</h1>
  </div>
  <div class="osb_content">
    <p>
      Payments Collection, Tax Summary, Revenue by Client and more insightful reports!
    </p>
    <a class="btn_large" href="/reports">See my reports</a>
  </div>
</div><!--overview_box-->

app/views/dashboard/_outstanding_invoices.html.erb
<div class="overview_box_heading">
  <h1>Outstanding Invoices <span>(USD)</span></h1>
</div>
<div class="graff_description">
  <div class="graff_value">
    <div class="graff_digit">
      <ul>
        <li class="digit_content"><%= number_to_currency(@outstanding_invoices) %></li>
        <li class="digit_description">Total Outstanding <span>(USD)</span></li>
      </ul>
    </div>
  </div><!--graff_value-->
  <div class="graff_detail">
    <table cellspacing="0" cellpadding="0">
      <tbody>
        <tr>
          <td>0 - 30 days old<span>:</span></td>
          <td><%= number_to_currency(@aged_invoices.attributes["zero_to_thirty"]) %></td>
        </tr>
        <tr>
          <td>30 - 60 days old<span>:</span></td>
          <td><%= number_to_currency(@aged_invoices.attributes["thirty_one_to_sixty"]) %></td>
        </tr>
        <tr>
          <td>60 - 90 days old<span>:</span></td>
          <td><%= number_to_currency(@aged_invoices.attributes["sixty_one_to_ninety"]) %></td>
        </tr>
        <tr>
          <td>Over 90 days old<span>:</span></td>
          <td><%= number_to_currency(@aged_invoices.attributes["ninety_one_and_above"]) %></td>
        </tr>
      </tbody>
    </table>
    <a href="/reports/aged_accounts_receivable">Account Aging Report</a>
  </div><!--graff_detail-->
</div><!--graff_description-->

app/views/dashboard/_recent_activity.html.erb
<div class="activity_wrapper">
  <div class="dashboard_box">
    <h1 class="small">Recent Activity</h1>

    <div class="grid_table activity">
      <table cellpadding="0" cellspacing="0" class="table table_listing invoice_listing">
        <colgroup>
          <col class="one"/>
          <col class="two"/>
          <col class="three"/>
          <col class="four"/>
        </colgroup>
        <% if @recent_activity.blank? %>
            <tr>
              <td colspan="4">No recent activity</td>
            </tr>
        <% else %>
            <%- @recent_activity.each do |activity| %>
                <tr>
                  <td class="align_left"><%= link_to activity[:activity_type].capitalize, activity[:activity_path] %></a></td>
                  <td class="align_left"><%= number_to_currency(activity[:amount]) %> <span>(USD)</span></td>
                  <td class="align_left"><%= "#{activity[:activity_action]} #{activity[:client]} on" %> </td>
                  <td class="align_left"><%= "#{activity[:activity_date].to_date}" %> </td>
                </tr>
            <% end %>
        <% end %>
      </table>
    </div>
    <!--grid_table-->
  </div>
  <!--overview_box-->
</div>

app/views/dashboard/index.erb
<div class="dashboard_style">
  <div class="row-fluid">
    <div class="span12">
      <div class="dashboart_menu">
        <ul>
          <li><%= link_to "New Invoice", new_invoice_path %></li>
          <li><%= link_to "New Item", new_item_path, :class => "small" %></li>
          <li><%= link_to "New Client", new_client_path, :class => "small" %></li>
          <li><%= link_to "New Payment", '/invoices/unpaid_invoices', "data-toggle" => "modal", "data-target" => "#myModal", :remote => true %></li>
        </ul>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
        <%= render "chart_container" %>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span12">
        <div class="amount_wrapper">
          <div class="dashboard_box">

            <div class="amount_box">
              <h1>YTD Income</h1>

              <h1 class="black"><%= number_to_currency(@ytd_income) %></h1>

              <p>Total amount received against invoices sent during this year</p>
            </div>

            <div class="amount_box">
              <h1>Amount Billed</h1>

              <h1 class="black"><%= number_to_currency(@amount_billed) %></h1>

              <p>Sum of the invoices total you sent to clients so far</p>
            </div>

            <div class="amount_box">
              <h1>Total Outstanding</h1>

              <h1 class="black"><%= number_to_currency(@outstanding_invoices) %></h1>

              <p>Total amount clients owe you</p>
            </div>

            <div class="amount_box">
              <h1>Aged AR</h1>

              <div class="days_summary">
                <div class="amount_row">
                  <div class="days">0 - 30 days old <span>:</span></div>
                  <div class="value"><%= number_to_currency(@aged_invoices.attributes["zero_to_thirty"]) || '$0.00' %></div>
                </div>
                <div class="amount_row">
                  <div class="days">30 - 60 days old <span>:</span></div>
                  <div class="value"><%= number_to_currency(@aged_invoices.attributes["thirty_one_to_sixty"]) || '$0.00' %></div>
                </div>
                <div class="amount_row">
                  <div class="days">60 - 90 days old <span>:</span></div>
                  <div class="value"><%= number_to_currency(@aged_invoices.attributes["sixty_one_to_ninety"]) || '$0.00' %></div>
                </div>
                <div class="amount_row">
                  <div class="days">Over 90 days old <span>:</span></div>
                  <div class="value"><%= number_to_currency(@aged_invoices.attributes["ninety_one_and_above"]) || '$0.00' %></div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

    <div class="row-fluid">

      <div class="span6">
        <div class="dashboard_box small right">
          <h1>Current Invoices</h1>
          <p></p>
          <div class="grid_table current_invoices top">
            <table cellpadding="0" cellspacing="0" class="table table_listing invoice_listing">
              <colgroup>
                <col class="one"/>
                <col class="two"/>
                <col class="three"/>
                <col class="four"/>
              </colgroup>
              <th class="align_left">Invoice#</th>
              <th class="align_left">Client</th>
              <th class="align_left">Due date</th>
              <th class="align_right">Amount</th>
            </table>
          </div>
          <!--grid_table-->
          <div class="scrollContainer content_scroll mCustomScrollbar">
            <div class="grid_table current_invoices btm mCustomScrollBox mCS-light">
              <table cellpadding="0" cellspacing="0" class="table table_listing invoice_listing mCSB_container">
                <colgroup>
                  <col class="one"/>
                  <col class="two"/>
                  <col class="three"/>
                  <col class="four"/>
                </colgroup>
                <tbody>
                <% if @current_invoices.blank? %>
                    <tr>
                      <td colspan="4">No current invoices</td>
                    </tr>
                <% else %>
                    <% @current_invoices.each do |current_invoice| %>
                        <tr>
                          <td class="align_left"><%= link_to current_invoice.invoice_number, invoice_path(current_invoice) %></td>
                          <td class="align_left"><%= current_invoice.client.organization_name rescue "" %></td>
                          <td class="align_left"><%= (current_invoice.due_date || current_invoice.invoice_date).to_time.strftime("%m/%d/%Y") rescue "" %></td>
                          <td class="align_right"><%= number_to_currency(current_invoice.invoice_total) %></td>
                        </tr>
                    <% end %>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <!--grid_table-->
        </div>
      </div>

      <div class="span6">
        <div class="dashboard_box small right">
          <h1>Past Invoices</h1>
          <p></p>
          <div class="grid_table current_invoices top">
            <table cellpadding="0" cellspacing="0" class="table table_listing invoice_listing">
              <colgroup>
                <col class="one"/>
                <col class="two"/>
                <col class="three"/>
                <col class="four"/>
              </colgroup>
              <th class="align_left">Invoice#</th>
              <th class="align_left">Client</th>
              <th class="align_left">Due date</th>
              <th class="align_right">Amount</th>
            </table>
          </div>
          <!--grid_table-->
          <div class="scrollContainer content_scroll mCustomScrollbar">
            <div class="grid_table current_invoices btm mCustomScrollBox mCS-light">
              <table cellpadding="0" cellspacing="0" class="table table_listing invoice_listing mCSB_container">
                <colgroup>
                  <col class="one"/>
                  <col class="two"/>
                  <col class="three"/>
                  <col class="four"/>
                </colgroup>
                <tbody>
                <% if @past_invoices.blank? %>
                    <tr>
                      <td colspan="4">No past invoices</td>
                    </tr>
                <% else %>
                    <% @past_invoices.each do |past_invoice| %>
                        <tr>
                          <td class="align_left"><%= link_to past_invoice.invoice_number, invoice_path(past_invoice) %></td>
                          <td class="align_left"><%= past_invoice.client.organization_name rescue "" %></td>
                          <td class="align_left"><%= (past_invoice.due_date || past_invoice.invoice_date).to_time.strftime("%m/%d/%Y") rescue "" %></td>
                          <td class="align_right"><%= number_to_currency(past_invoice.invoice_total) %></td>
                        </tr>
                    <% end %>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <!--grid_table-->
        </div>
      </div>

    </div>
    <!--row-fluid-->

    <div class="row-fluid">
      <div class="span12">


        <%= render "recent_activity" %>
      </div>
    </div>

  </div>
</div>
<!-- START: Unpaid invoices popup -->
<%= form_tag "/payments/enter_payment", :id => "invoice_selection" do %>
    <div id="myModal" class="modal hide fad" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="model_grey_container">
        <div class="modal-header">

          <h1>Which Invoices have you received payment for?</h1>

          <p>Select one or more Invoices from the list below to apply payment.</p>

          <div class="cross_btn">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
              <%= image_tag "cross.png", :size => "7x7", :alt => "" %>
            </button>
          </div>
        </div>
        <div id="invoice_popup_error" class="alert alert-error popup" style="display:none;">
          <button class="close" type="button" style="margin:0px;">×</button>
          <table>
            <tbody>
            <tr>
              <td>
                <span>You haven't selected any invoice. Please select one or more invoices and try again.</span>
              </td>
            </tr>
            </tbody>
          </table>
        </div>
        <div class="modal-body">
        </div>
        <div class="footer ">
          <%= submit_tag "Enter Payment", :class => "btn_large submit" %>
          <a class="btn_large grey" href="#" data-dismiss="modal">cancel</a>
        </div>
      </div>
    </div>
<% end %>
<!-- END: Unpaid invoices popup -->

app/views/dashboard/index_new.erb
<div class="dashboard_style">
  <div class="row-fluid">
    <div class="span4">
      <%= render "getting_started" %>
      <%= render "recent_activity" %>
      <%= render "osb_reports" %>
    </div>
    <!--span4-->
    <div class="span8">
      <div class="overview_box">
        <%= render "chart_container" %>
        <%= render "outstanding_invoices" %>
      </div>
      <!--overview_box-->
    </div>
    <!--span8-->
  </div>
  <!--row-fluid-->
</div>

<!-- START: Unpaid invoices popup -->
<%= form_tag "/payments/enter_payment", :id => "invoice_selection" do %>
    <div id="myModal" class="modal hide fad" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="model_grey_container">
        <div class="modal-header">

          <h1>Which Invoices have you received payment for?</h1>

          <p>Select one or more Invoices from the list below to apply payment.</p>

          <div class="cross_btn">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
              <%= image_tag "cross.png", :size => "7x7", :alt => "" %>
            </button>
          </div>
        </div>
        <div id="invoice_popup_error" class="alert alert-error popup" style="display:none;">
          <button class="close" type="button" style="margin:0px;">×</button>
          <table>
            <tbody>
            <tr>
              <td>
                <span>You haven't selected any invoice. Please select one or more invoices and try again.</span>
              </td>
            </tr>
            </tbody>
          </table>
        </div>
        <div class="modal-body">
        </div>
        <div class="footer ">
          <%= submit_tag "Enter Payment", :class => "btn_large submit" %>
          <a class="btn_large grey" href="#" data-dismiss="modal">cancel</a>
        </div>
      </div>
    </div>
<% end %>
<!-- END: Unpaid invoices popup -->