config/routes.rb
Osb::Application.routes.draw do

  resources :sub_users

  resources :payment_terms

  resources :companies

  match "help" => "help#index"
  match "reports/:report_name" => "reports#reports"
  match "reports/data/:report_name" => "reports#reports_data"
  match "reports" => "reports#index"

  match "dashboard" => "dashboard#index"
  resources :payments do
    collection do
      get 'enter_payment'
      put 'update_individual_payment'
      get 'filter_payments'
      get 'bulk_actions'
      get 'undo_actions'
      get 'payments_history'
      get 'invoice_payments_history'
    end
  end
  resources :taxes do
    collection do
      get 'filter_taxes'
      get 'bulk_actions'
      get 'undo_actions'
    end
  end

  match "invoices/unpaid_invoices" => "invoices#unpaid_invoices"

  resources :clients do
    collection do
      get 'filter_clients'
      get 'bulk_actions'
      post 'get_last_invoice'
      get 'undo_actions'
    end
  end

  resources :client_contacts

  devise_for :users, :path_names => {:sign_out => 'logout'}

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

  resources :items do
    collection do
      get 'filter_items'
      get 'bulk_actions'
      post 'load_item_data'
      get 'duplicate_item'
      get 'undo_actions'
    end
  end

  resources :invoice_line_items

  resources :invoices do
    resources :invoice_line_items
    collection do
      get 'filter_invoices'
      get 'bulk_actions'
      get 'undo_actions'
      post 'duplicate_invoice'
      get 'enter_single_payment'
      get 'send_invoice'
      post 'paypal_payments'
      get 'preview'
      get 'credit_card_info'
    end
  end

  resources :company_profiles

  resources :client_additional_contacts

  resources :clients

  resources :sent_emails

  root :to => redirect("/dashboard")

  match ':controller(/:action(/:id))(.:format)'
end

app/models/payment_term.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
class PaymentTerm < ActiveRecord::Base
  # attr
  attr_accessible :description, :number_of_days

  # associations
  has_many :invoices
end

app/controllers/payment_terms_controller.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
class PaymentTermsController < ApplicationController
  # GET /payment_terms
  # GET /payment_terms.json
  def index
    @payment_terms = PaymentTerm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payment_terms }
    end
  end

  # GET /payment_terms/1
  # GET /payment_terms/1.json
  def show
    @payment_term = PaymentTerm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment_term }
    end
  end

  # GET /payment_terms/new
  # GET /payment_terms/new.json
  def new
    @payment_term = PaymentTerm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment_term }
    end
  end

  # GET /payment_terms/1/edit
  def edit
    @payment_term = PaymentTerm.find(params[:id])
  end

  # POST /payment_terms
  # POST /payment_terms.json
  def create
    @payment_term = PaymentTerm.new(params[:payment_term])

    respond_to do |format|
      if @payment_term.save
        format.js #if params[:quick_create]
        format.json { render :json => @payment_term, :status => :created, :location => @payment_term }
      else
        format.html { render action: "new" }
        format.json { render json: @payment_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payment_terms/1
  # PUT /payment_terms/1.json
  def update
    @payment_term = PaymentTerm.find(params[:id])

    respond_to do |format|
      if @payment_term.update_attributes(params[:payment_term])
        format.html { redirect_to @payment_term, notice: 'Payment term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_terms/1
  # DELETE /payment_terms/1.json
  def destroy
    @payment_term = PaymentTerm.find(params[:id])
    @payment_term.destroy

    respond_to do |format|
      format.html { redirect_to payment_terms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/payment_terms_helper.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
module PaymentTermsHelper
end

app/views/payment_terms/_form.html.erb
<%= form_for(@payment_term) do |f| %>
    <% if @payment_term.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@payment_term.errors.count, "error") %> prohibited this payment_term from being saved:</h2>

          <ul>
            <% @payment_term.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :number_of_days %>
      <br/>
      <%= f.number_field :number_of_days %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <br/>
      <%= f.text_field :description %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/payment_terms/_new_term.html.erb
<div class="tiny_form_container">
  <div id="create_client" class="tiny_create_form">
    <div class="tiny_form_inner">

<%#= form_tag "/payment_terms/create", :id => "create_term", :remote => true do %>

      <div class="tiny_form_top">
        <div class="tiny_form_heading"><h4>Add New Payment Term</h4></div>
        <div class="close_btn"><%= link_to 'x', 'javascript:' %></div>
      </div>
      <!--tiny_form_top-->

      <div class="tiny_form_middle">

        <div class="fields_content_data">

          <div class="field_row">
            <div class="label_field left"><span>Number of days</span></div>
            <div class="small_field">
              <%= text_field_tag "payment_term[number_of_days]", '', :required => 'required' %>
            </div>
          </div>
          <!--field_row-->

          <div class="field_row">
            <div class="label_field left single"><span>Description</span></div>
            <div class="small_field">
              <%= text_field_tag "payment_term[description]", '', :required => 'required' %>
              <%= hidden_field_tag :quick_create %>
            </div>
          </div>
          <!--field_row-->

          <div id="clientModal" class="client-modal">
            <div class="cross_btn">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                <%= image_tag "cross.png", :size => "7x7", :alt => "" %>
              </button>
            </div>
          </div>
        </div>
        <!--fields_content_data-->
      </div>
      <!--tiny_form_middle-->

      <div class="tiny_form_btm">
<%#= submit_tag "save", :name => "save", :class => "btn_large", :style => "width:40px;" %>
<%#= submit_tag "save & ADD MORE", :name => "add_more", :class => "btn_large" %>
        <%= button_tag "save", :name => "save", :class => "btn_large tiny_btn btn_save", :style => "width:40px;" %>
        <%= button_tag "save & Add More", :name => "add_more", :class => "btn_large tiny_btn btn_save_and_add_more" %>
      </div>
      <!--tiny_form_btm-->

    </div>
    <!--tiny_form_inner-->
  </div>
  <!--tiny_create_form-->
</div><!--tiny_form_container-->
<%# end %>

app/views/payment_terms/create.js.erb
<% inlineform_action = params[:add_more] ? "inlineform:save_and_add_more" : "inlineform:save" %>
<%= "{\"action\": \"#{inlineform_action}\", \"record\": \"<option value='#{@payment_term.id}' number_of_days='#{@payment_term.number_of_days}' selected>#{@payment_term.description}</option>\"}".html_safe%>

app/views/payment_terms/edit.html.erb
<h1>Editing payment_term</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_term %> |
<%= link_to 'Back', payment_terms_path %>

app/views/payment_terms/index.html.erb
<h1>Listing payment_terms</h1>

<table>
  <tr>
    <th>Number of days</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @payment_terms.each do |payment_term| %>
      <tr>
        <td><%= payment_term.number_of_days %></td>
        <td><%= payment_term.description %></td>
        <td><%= link_to 'Show', payment_term %></td>
        <td><%= link_to 'Edit', edit_payment_term_path(payment_term) %></td>
        <td><%= link_to 'Destroy', payment_term, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Payment term', new_payment_term_path %>

app/views/payment_terms/new.html.erb
<h1>New payment_term</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_terms_path %>

app/views/payment_terms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number of days:</b>
  <%= @payment_term.number_of_days %>
</p>

<p>
  <b>Description:</b>
  <%= @payment_term.description %>
</p>


<%= link_to 'Edit', edit_payment_term_path(@payment_term) %> |
<%= link_to 'Back', payment_terms_path %>