config/routes.rb
Osb::Application.routes.draw do

  resources :sub_users

  resources :payment_terms

  resources :companies

  match "help" => "help#index"
  match "reports/:report_name" => "reports#reports"
  match "reports/data/:report_name" => "reports#reports_data"
  match "reports" => "reports#index"

  match "dashboard" => "dashboard#index"
  resources :payments do
    collection do
      get 'enter_payment'
      put 'update_individual_payment'
      get 'filter_payments'
      get 'bulk_actions'
      get 'undo_actions'
      get 'payments_history'
      get 'invoice_payments_history'
    end
  end
  resources :taxes do
    collection do
      get 'filter_taxes'
      get 'bulk_actions'
      get 'undo_actions'
    end
  end

  match "invoices/unpaid_invoices" => "invoices#unpaid_invoices"

  resources :clients do
    collection do
      get 'filter_clients'
      get 'bulk_actions'
      post 'get_last_invoice'
      get 'undo_actions'
    end
  end

  resources :client_contacts

  devise_for :users, :path_names => {:sign_out => 'logout'}

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

  resources :items do
    collection do
      get 'filter_items'
      get 'bulk_actions'
      post 'load_item_data'
      get 'duplicate_item'
      get 'undo_actions'
    end
  end

  resources :invoice_line_items

  resources :invoices do
    resources :invoice_line_items
    collection do
      get 'filter_invoices'
      get 'bulk_actions'
      get 'undo_actions'
      post 'duplicate_invoice'
      get 'enter_single_payment'
      get 'send_invoice'
      post 'paypal_payments'
      get 'preview'
      get 'credit_card_info'
    end
  end

  resources :company_profiles

  resources :client_additional_contacts

  resources :clients

  resources :sent_emails

  root :to => redirect("/dashboard")

  match ':controller(/:action(/:id))(.:format)'
end

app/models/company.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
class Company < ActiveRecord::Base
  # attr
  attr_accessible :admin_billing_rate_per_hour, :admin_email, :admin_first_name, :admin_last_name, :admin_password, :admin_user_name, :auto_dst_adjustment, :city, :country, :currency_symbol, :currency_code, :email, :fax, :org_name, :phone_business, :phone_mobile, :postal_or_zip_code, :profession, :province_or_state, :street_address_1, :street_address_2, :time_zone, :created_at, :updated_at

  # associations
  has_and_belongs_to_many :users, :join_table => 'company_users'

  # callbacks
  before_save :change_currency_symbol

  def change_currency_symbol
    self.currency_symbol = CURRENCY_SYMBOL[self.currency_code]
  end
end

app/controllers/companies_controller.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = current_user.companies

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    user_company = current_user.companies
    if user_company.present?
      @company = user_company.first
      redirect_to edit_company_url(@company)
    else
      @company = user_company.build
      respond_to { |format| format.html }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = current_user.companies.build(params[:company])

    respond_to do |format|
      if current_user.save
        format.html { redirect_to edit_company_url(@company), notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end

    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to edit_company_url(@company), notice: 'Your company profile has been updated successfully.'}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    current_user.companies.destroy(@company)

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/companies_helper.rb
#
# Open Source Billing - A super simple software to create & send invoices to your customers and
# collect payments.
# Copyright (C) 2013 Mark Mian <mark.mian@opensourcebilling.org>
#
# This file is part of Open Source Billing.
#
# Open Source Billing is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Open Source Billing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Open Source Billing.  If not, see <http://www.gnu.org/licenses/>.
#
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company, :html => {:novalidate => ""}) do |f| %>
  <div class="content_middle">
    <div class="fields_content">
      <div class="fields_content_container">

        <div class="fields_content_data">

          <div class="field_row">
            <div class="label_field left single">
              <%#= f.label "company_name" %>
              <label for="company_org_name"><span>Company Name</span></label>
            </div>
            <div class="middle_field">
              <%= f.text_field :org_name, :required => 'required' %>
            </div>
          </div>
          <!--field_row-->

          <div class="field_row">
            <div class="label_field left single">
              <%#= f.label "first_name" %>
              <label for="company_admin_first_name"><span>First Name</span></label>
            </div>
            <div class="middle_field">
              <%= f.text_field :admin_first_name, :required => 'required' %>
            </div>
          </div>
          <!--field_row-->

          <div class="field_row">
            <div class="label_field left single">
              <%#= f.label "last_name" %>
              <label for="company_admin_last_name"><span>Last Name</span></label>
            </div>
            <div class="middle_field">
              <%= f.text_field :admin_last_name, :required => 'required' %>
            </div>
          </div>
          <!--field_row-->

          <div class="field_row">
            <div class="label_field left single">
              <%= f.label :country %>
            </div>
            <div class="middle_field">
              <%= f.select :country, COUNTRY_LIST, {:prompt => ""}, {"data-placeholder" => "Select a country...", :class => "chzn-select"} %>
              <%#= f.text_field :country %>
            </div>
          </div>
          <!--field_row-->

          <div class="field_row">
            <div class="label_field left single">
              <label for="company_street_address_1">Street Address</label>
            </div>
            <div class="middle_field">
              <%= f.text_field :street_address_1 %>
            </div>
          </div>
          <!--field_row-->

          <div class="field_row">
            <div class="label_field left single">
              <%= f.label " " %>
            </div>
            <div class="middle_field">
              <%= f.text_field :street_address_2 %>
            </div>
          </div>
          <!--field_row-->

          <div class="field_row">
            <div class="label_field left single">
              <%= f.label :city %>
            </div>
            <div class="middle_field">
              <%= f.text_field :city %>
            </div>
          </div>
          <!--field_row-->

          <div class="field_row">
            <div class="label_field left single">
              <label for="company_province_or_state">Province/State</label>
            </div>
            <div class="middle_field">
              <%= f.text_field :province_or_state %>
            </div>
          </div>
          <!--field_row-->

          <div class="field_row">
            <div class="label_field left single">
              <label for="company_postal_or_zip_code">Postal/Zip code</label>
            </div>
            <div class="middle_field">
              <%= f.text_field :postal_or_zip_code %>
            </div>
          </div>
          <!--field_row-->

          <div class="field_row">
            <div class="label_field left single">
              <label for="company_phone_business">Phone Number</label>
            </div>
            <div class="middle_field">
              <%= f.text_field :phone_business %>
            </div>
          </div>
          <!--field_row-->

        </div><!--fields_content_data-->
        <script>$(".fields_content").last().css('border-bottom', 'none');</script>

      </div>
      <!--fields_content_container-->
    </div>
    <!--fields_content-->
  </div>
  <!--content_middle-->
<%#= render 'location_setting',:f=>f %>

  <div class="content_bottom">
    <%= f.submit :class => "btn_large submit" %>
  </div><!--content_bottom-->

<% end %>

app/views/companies/_location_setting.html.erb
<div class="content_top">
  <div class="primary_heading">
    <h1>Location Settings</h1>
  </div>
</div>
<!--content_top-->

<div class="content_middle">
  <div class="fields_content">
    <div class="fields_content_container">

      <div class="fields_content_data">

        <div class="field_row">
          <div class="label_field left single">
            <%= f.label :currency_code %>
          </div>
          <div class="middle_field">
            <%= f.select :currency_code, CURRENCY_CODE, {:prompt => ""}, {"data-placeholder" => "Select a currency code...", :class => "chzn-select"} %>
          </div>
        </div>
        <!--field_row-->

        <div class="field_row">
          <div class="label_field left single">
            <%= f.label :time_zone %>
          </div>
          <div class="middle_field">
            <%= f.select :time_zone, ActiveSupport::TimeZone.all, {:prompt => ""}, {"data-placeholder" => "Select a time zone...", :class => "chzn-select"} %>
            <%#= f.text_field :time_zone %>
          </div>
        </div>
        <!--field_row-->

      </div>
      <!--fields_content_data-->

    </div>
    <!--fields_content_container-->
  </div><!--fields_content-->
  <script>$(".fields_content").last().css('border-bottom', 'none');</script>
</div>
<!--content_middle-->

app/views/companies/edit.html.erb
<div class="content_top">
  <div class="primary_heading">
    <h1>Company Profile</h1>
  </div>
</div>
<!--content_top-->

<div class="companies_wrapper">
  <%= render 'form' %>
</div>

<%#= link_to 'Show', @company %>
<%#= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>
<table>
  <tr>
    <th>Org name</th>
    <th>Country</th>
    <th>Street address 1</th>
    <th>Street address 2</th>
    <th>City</th>
    <th>Province or state</th>
    <th>Postal or zip code</th>
    <th>Profession</th>
    <th>Phone business</th>
    <th>Phone mobile</th>
    <th>Fax</th>
    <th>Email</th>
    <th>Time zone</th>
    <th>Auto dst adjustment</th>
    <th>Currency code</th>
    <th>Currecy symbol</th>
    <th>Admin first name</th>
    <th>Admin last name</th>
    <th>Admin email</th>
    <th>Admin billing rate per hour</th>
    <th>Admin user name</th>
    <th>Admin password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @companies.each do |company| %>
      <tr>
        <td><%= company.org_name %></td>
        <td><%= company.country %></td>
        <td><%= company.street_address_1 %></td>
        <td><%= company.street_address_2 %></td>
        <td><%= company.city %></td>
        <td><%= company.province_or_state %></td>
        <td><%= company.postal_or_zip_code %></td>
        <td><%= company.profession %></td>
        <td><%= company.phone_business %></td>
        <td><%= company.phone_mobile %></td>
        <td><%= company.fax %></td>
        <td><%= company.email %></td>
        <td><%= company.time_zone %></td>
        <td><%= company.auto_dst_adjustment %></td>
        <td><%= company.currency_code %></td>
        <td><%= company.currency_symbol %></td>
        <td><%= company.admin_first_name %></td>
        <td><%= company.admin_last_name %></td>
        <td><%= company.admin_email %></td>
        <td><%= company.admin_billing_rate_per_hour %></td>
        <td><%= company.admin_user_name %></td>
        <td><%= company.admin_password %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<div class="content_top">
  <div class="primary_heading">
    <h1>Company Profile</h1>
  </div>
</div>
<!--content_top-->

<div class="companies_wrapper">
  <%= render 'form' %>
</div>

<%#= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Org name:</b>
  <%= @company.org_name %>
</p>

<p>
  <b>Country:</b>
  <%= @company.country %>
</p>

<p>
  <b>Street address 1:</b>
  <%= @company.street_address_1 %>
</p>

<p>
  <b>Street address 2:</b>
  <%= @company.street_address_2 %>
</p>

<p>
  <b>City:</b>
  <%= @company.city %>
</p>

<p>
  <b>Province or state:</b>
  <%= @company.province_or_state %>
</p>

<p>
  <b>Postal or zip code:</b>
  <%= @company.postal_or_zip_code %>
</p>

<p>
  <b>Profession:</b>
  <%= @company.profession %>
</p>

<p>
  <b>Phone business:</b>
  <%= @company.phone_business %>
</p>

<p>
  <b>Phone mobile:</b>
  <%= @company.phone_mobile %>
</p>

<p>
  <b>Fax:</b>
  <%= @company.fax %>
</p>

<p>
  <b>Email:</b>
  <%= @company.email %>
</p>

<p>
  <b>Time zone:</b>
  <%= @company.time_zone %>
</p>

<p>
  <b>Auto dst adjustment:</b>
  <%= @company.auto_dst_adjustment %>
</p>

<p>
  <b>Currency code:</b>
  <%= @company.currency_code %>
</p>

<p>
  <b>Currecy symbol:</b>
  <%= @company.currency_symbol %>
</p>

<p>
  <b>Admin first name:</b>
  <%= @company.admin_first_name %>
</p>

<p>
  <b>Admin last name:</b>
  <%= @company.admin_last_name %>
</p>

<p>
  <b>Admin email:</b>
  <%= @company.admin_email %>
</p>

<p>
  <b>Admin billing rate per hour:</b>
  <%= @company.admin_billing_rate_per_hour %>
</p>

<p>
  <b>Admin user name:</b>
  <%= @company.admin_user_name %>
</p>

<p>
  <b>Admin password:</b>
  <%= @company.admin_password %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>